const ShopActionTypes = {
    FETCH_ALL_PRODUCTS_START: 'FETCH_ALL_PRODUCTS_START',
    FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILURE: 'FETCH_ALL_PRODUCTS_FAILURE',
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    SET_PRODUCTS_PAGER: 'SET_PRODUCTS_PAGER'
  };
  
  export default ShopActionTypes;